language: python
dist: bionic
cache: pip
env:
  - PYTHONHASHSEED=0
install:
  - make travis-setup
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  # PyPy versions
  - "pypy3"
script:
  - make ci

jobs:
  include:
    - stage: coverage
      python:
        - "3.6"
      script:
        - make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
