sudo: false
language: python
cache: pip
env:
  - PYTHONHASHSEED=0
install:
  - make travis-setup
jobs:
  include:
    - stage: test
      python:
        - 2.7
        - 3.4
        - 3.5
        - 3.6
        - 3.7
        # PyPy versions
        - 'pypy'
        - 'pypy3'
        script:
          - make ci
    - stage: coverage
      python:
        - 2.7
        - 3.6
      script:
        - make coverage
      after_success:
        - coveralls
